#!/usr/bin/env ruby
# frozen_string_literal: true

require 'mcsmp'
require 'thor'
autoload :MCSMP, 'lib/mcsmp'

# The main CLI
class MCSMPCLI < Thor
  desc 'run PATH', 'Run a MineCraft instance at the target PATH'
  def run_server(path = File.absolute_path(Dir.pwd))
    instance = MCSMP::ServerInstance.from_existing(path)
    runner = MCSMP::ServerRunner.new(instance)
    runner.start_sync
  end

  desc 'pry PATH', 'Run an PRY console at the target folder and get all'\
    'server instances in it'
  def pry_start(path = File.absolute_path(Dir.pwd))
    require 'pry'

    instances = MCSMP::Util.get_instances(path)
    runners = autostart_instances(instances)
    pry(Struct.new(:instances, :runners).new(instances, runners))

  rescue GemNotFoundException
    warn 'Install PRY to use this option: gem install pry'
  end

  private

  def autostart_instances(instances)
    runners = []
    instances.each do |instance|
      next unless File.exist?(File.join(instance.physical_path, '.autostart'))

      runner = MCSMP::ServerRunner.new(instance)
      runner.start_async
      runners.push(runner)
    end
    runners
  end
end

MCSMPCLI.start
